### ISSUE TITLE
Port change doesn't work...

### ISSUE THREAD

**Issue by leonard4** [astuto/astuto#173]
I've edited the docker-compose.yml file and set my port to 80:80 but the feedback-web container still launches on port 3000, any ideas? I'm not very familiar with docker, thanks! Also is there any way to increase the amount of threads from 5 to something higher? 

![image](https://user-images.githubusercontent.com/1154391/204710035-4659ab88-f23c-48e5-9ead-1cfc1c5747ec.png)

**Comment by riggraz** [comment]
Hi Leonard,

Unfortunately it seems like the port specified in the docker-compose is not taken into consideration.

If you're running Astuto in production, try to change `docker-entrypoint-prod.sh` and change the last line to: `bundle exec rails server -e production -p 80`. Otherwise, if you're in development, change `docker-entrypoint-dev.sh` last line from port 3000 to 80.

Let me know if this temporary solution works for you 😄

**Comment by leonard4** [comment]
@riggraz Thanks for the response! Looks like that would probably work but I know zero about docker so I don't know where/how to edit that file. :) Astuto install was my first time using Docker so I'm super new to this.

**Comment by riggraz** [comment]
Hey @leonard4, happy to hear that!

Indeed it is not possible to change the internal port (it is always 3000), but you can redirect your local 80 to internal 3000. I didn't think about it, but I believe this is not a bug and shouldn't be fixed.

Thanks for sharing your solution!
