### ISSUE TITLE
Function of the Demo App

### ISSUE THREAD

**Issue by mknooihuisen** [astuto/astuto#198]
The name and email for the demo user (admin @ example.org) imply that this user has Admin power in the demo, but they are only a Moderator.  I can understand why you might do this for security, but it makes it look like Astuto doesn't have common Admin controls.  Running the Docker image locally is fairly simple, but loading the existing demo is even simpler, so many people won't go any further if it looks like the app is missing the basics.

**Suggested Fix:** Create a cron job (repeated, automated task) on your demo server to restore the Postgres DB from a pre-made backup every hour or two.  That way, you can grant the demo user admin powers and show off everything Astuto can do, without allowing lasting change on the demo site.

Of course, running the Docker image locally isn't hard, but it's a step that might be skipped if the demo looks like it lacks the basics.

It's a promising project, though!  Nice work! 👍

**Comment by riggraz** [comment]
Hi, thanks for reaching out!

A few months ago the admin user had all privileges, but I removed it because some people where using it to delete everything and mess up the demo. Your cron job solution is clever, but since I'm planning to offer a saas plan for Astuto, I'll add the possibility to try it out for free for 2 weeks or so, and the current demo instance will be deleted.

Thanks anyways for your suggestion! Bye 👋🏻
