### ISSUE TITLE
Disable email confirmation for creating new users

### ISSUE THREAD

**Issue by P0ulp1** [astuto/astuto#275]
I'm trying to disable the email confirmation feature by setting the EMAIL_CONFIRMATION variable to "False" but it's not working.
Is it even a feature?

**Comment by riggraz** [comment]
Hi P0ulp1, unfortunately the `EMAIL_CONFIRMATION` variable is not supported anymore (even though the documentation refers to it... i'm going to update it).

However, if you want to try a registration in development mode you can just check docker logs: the confirmation email will show up here and you can copy paste the activation link to your browser.

Otherwise, if you are in a production environment, you must either set up SMTP in order to send email confirmations, or add a OAuth provider. Users that logs in with OAuth providers are obviously automatically confirmed.

**Comment by P0ulp1** [comment]
Alright, thanks for the reply and this great app!
