### ISSUE TITLE
Use FactoryBot::Syntax::Methods in the specs

### ISSUE THREAD

**Issue by Vin0uz** [astuto/astuto#45]
Everywhere in the spec, `FactoryBot.create` is called. It's not too bad, but it could be a simple `create` and be as efficient.

This is the usage proposed by [factory_bot in Rspec getting started](https://github.com/thoughtbot/factory_bot/blob/master/GETTING_STARTED.md#rspec)

It would required to add a ittle piece of code in rails_helper, or even better in a dedicated support file, and replace `FactoryBot.create`calls by `create`

**Comment by riggraz** [comment]
I'm okay with this since it will reduce the length of lines of code in specs and speed up spec writing (which is really good). However we should be aware that we lose in explicitness, so newcomers may not understand that, for example, `.build()` is actually `FactoryBot.build()`: we can solve this by adding a little bit of documentation in wikis or contributing guidelines.

Same goes for issue #46 !

**Comment by riggraz** [comment]
Let's keep it the way it is: longer but clearer!
